{{- if .Values.deployment }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: default
          image: "{{ .Values.image.repo }}:{{ .Values.image.tag}}"
          imagePullPolicy: {{ .Values.image.pullPolicy}}
          args: {{ .Values.args | toYaml | nindent 12 }}
{{- end }}
